### ISSUE TITLE
[FEATURE] - Chat Input

### ISSUE THREAD

**Issue by timbaton** [admiral-team/admiralui-flutter#102]
**Описание задачи:**
Реализовать компонент - https://www.figma.com/file/h7LytOq9qfvASRJD4uL34C/Admiral-Mobile-UI-Kit-(iOS)?node-id=10358%3A2918&t=cPGuQO1mYF4Rh5bM-4

Компонент для набора текстового сообщения или записи голосового сообщения, представлен в трех вариантах - незаполненный, активыный и заполненный.

**Comment by KirBorisov96** [comment]
2.0
