### ISSUE TITLE
[BUG] - Сопоставить дизайн главной страницы с фигмой

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-flutter#205]
**App version**: 1678718819
**OS version**: 16.1.1
**Описание**: 
> Подробное описание проблемы
Сопоставить дизайн главной страницы с фигмой, само название дизайн-системы 
iOS + Android

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
1 фото фигма
2 фото приложение
![image](https://user-images.githubusercontent.com/101252323/225748545-b50f522c-f2fb-4019-b808-2f5d3c674aa1.png)
![image](https://user-images.githubusercontent.com/101252323/225748588-3b458303-5abf-4873-86dd-62774f5c7b6b.png)

**Comment by Almazovivan** [comment]
Исправлены ошибки на главной страницы
![Simulator Screenshot - iPhone 12 Pro - 2024-01-25 at 18 02 42](https://github.com/admiral-team/admiralui-flutter/assets/66259778/4d70dcf6-9fd0-4824-9120-da2da1899565)
