### ISSUE TITLE
[BUG] - Нет строки поиска на главной странице

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-flutter#206]
**App version**: 1678718819
**OS version**: 16.1.1
**Описание**: 
> Подробное описание проблемы
Нет строки поиска на главной странице
iOS + Android
**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![image](https://user-images.githubusercontent.com/101252323/225748846-d4c6fd7d-7db1-4817-a462-54ef9d577131.png)

**Comment by KirBorisov96** [comment]
0.4d
