### ISSUE TITLE
[FEATURE] - В разделе Buttons - buttons должны быть с маленькой буквы

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-flutter#211]
**Описание задачи:**
В разделе Buttons - buttons должны быть с маленькой буквы

**Фреймворк**
Flutter
iOS + Android

**Ресурсы:**
Ссылка на макеты или ресурсы...

![image](https://user-images.githubusercontent.com/101252323/225749688-7bc49c8d-1ac3-4243-9475-0a2adc853f79.png)

**Comment by KirBorisov96** [comment]
0.1d
