### ISSUE TITLE
[FEATURE] - Icons и Currency

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-flutter#263]
**Описание задачи:**
Наименование раздела Icon - нужно добавить s на конце, чтоб было Currency
То же самое сделать и с Icon & Flags

**Фреймворк**
Flutter
iOS + Android

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by Almazovivan** [comment]
![Simulator Screenshot - iPhone 12 Pro - 2024-01-25 at 18 03 14](https://github.com/admiral-team/admiralui-flutter/assets/66259778/829fa32b-d54e-490c-baca-c9cee6845f05)
