### ISSUE TITLE
[BUG] - Поправить разделы в Currency

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-flutter#264]
**App version**: 1678718819
**OS version**: 16.1.1
**Описание**: 
> Разделы в Currency не соответствуют фигме, кидаю скрины, плюс поправить в каждом разделе "Наименование раздела"
iOS + Android

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

![image](https://user-images.githubusercontent.com/101252323/225837829-b290efcd-6447-4404-918c-5154aa599ab6.png)
![image](https://user-images.githubusercontent.com/101252323/225837843-a9f41ce7-88e7-4079-a332-94815f241abe.png)
![image](https://user-images.githubusercontent.com/101252323/225837868-5cd4f800-3cec-4b38-849e-488116535051.png)
![image](https://user-images.githubusercontent.com/101252323/225837881-2e23707f-632c-45c0-97e3-ca8a3a3dcf69.png)

![image](https://user-images.githubusercontent.com/101252323/225837941-b6588382-af13-4845-8a3d-a6ee36753325.png)

**Comment by Almazovivan** [comment]
![Simulator Screenshot - iPhone 12 Pro - 2024-01-24 at 17 48 23](https://github.com/admiral-team/admiralui-flutter/assets/66259778/2778d449-f112-4faa-ab4d-61e2c1c85b34)
