### ISSUE TITLE
[BUG] - Не правильный title

### ISSUE THREAD

**Issue by Andyatkov** [admiral-team/admiralui-flutter#438]
![Simulator Screenshot - iPhone 15 - 2024-03-12 at 10 17 58](https://github.com/admiral-team/admiralui-flutter/assets/8963238/9c2b3d05-df04-45db-b3de-2d66ad642b42)

Должен быть input

**Comment by Almazovivan** [comment]
Сделано в рамках реквеста https://github.com/admiral-team/admiralui-flutter/pull/460
