### ISSUE TITLE
[BUG] - Title на экранах informers не соответствуют дизайну

### ISSUE THREAD

**Issue by Andyatkov** [admiral-team/admiralui-flutter#441]
Пройтись по всем экранам демо по informers и заменить тайтл
![Simulator Screenshot - iPhone 15 - 2024-03-12 at 10 25 51](https://github.com/admiral-team/admiralui-flutter/assets/8963238/1a4e841b-fb43-451c-95fc-75a5e7a0aaab)
![Simulator Screenshot - iPhone 15 - 2024-03-12 at 10 25 56](https://github.com/admiral-team/admiralui-flutter/assets/8963238/1197fea6-0cfc-418f-b7e8-1a08149a7db5)

**Comment by Almazovivan** [comment]
Сделано в рамках реквеста https://github.com/admiral-team/admiralui-flutter/pull/460
