### ISSUE TITLE
[BUG] - Title page control не соотвествует дизайну

### ISSUE THREAD

**Issue by Andyatkov** [admiral-team/admiralui-flutter#443]
Поменять title на экране PageControl
ФР
![Simulator Screenshot - iPhone 15 - 2024-03-12 at 10 38 38](https://github.com/admiral-team/admiralui-flutter/assets/8963238/0fc05867-0404-4479-8999-7c5df3f750c3)
ОР
<img width="321" alt="Снимок экрана 2024-03-12 в 10 39 29" src="https://github.com/admiral-team/admiralui-flutter/assets/8963238/7c7299a5-42c7-4c08-9d71-46171b6ca462">

**Comment by Almazovivan** [comment]
Сделано в рамках реквеста https://github.com/admiral-team/admiralui-flutter/pull/460
