### ISSUE TITLE
[BUG] - Navigation bar на экране Links и Tags не меняет цвет

### ISSUE THREAD

**Issue by Andyatkov** [admiral-team/admiralui-flutter#461]
Нужно чтобы в темной теме nav bar менял цвет
и потом поправить тесты
ФР
![links_dark_screen_iPhone SE](https://github.com/admiral-team/admiralui-flutter/assets/8963238/2068ea7c-a6a8-4a89-b6d8-902a2a0ef749)
![Simulator Screenshot - iPhone 15 - 2024-03-21 at 11 26 46](https://github.com/admiral-team/admiralui-flutter/assets/8963238/9bb0044b-d321-4103-b4b0-d7b4ce2c42d7)

**Comment by Almazovivan** [comment]
Сделано в рамках реквеста https://github.com/admiral-team/admiralui-flutter/pull/460
