### ISSUE TITLE
[FEATURE] - Ресерч flutter for web. Setup and deploy server

### ISSUE THREAD

**Issue by KirBorisov96** [admiral-team/admiralui-flutter#93]
**Описание задачи:**
Краткое описание задачи...

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (Flutter)...

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by timbaton** [comment]
Web - GitHub pages, iOS, Android - app center

**Comment by timbaton** [comment]
в вебе должна быть возможность тестить фичи (сделать и дев, и прод)
iOS, android - два типа (прод, дев)
